// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-w3fRjkMovOwgDDq2piNOh08dSRnPNmM',
    appId: '1:306140297702:web:0e6a95ca2223dbba6c7e27',
    messagingSenderId: '306140297702',
    projectId: 'presensi-blockchain',
    authDomain: 'presensi-blockchain.firebaseapp.com',
    storageBucket: 'presensi-blockchain.appspot.com',
    measurementId: 'G-D1XN0K0EY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjsxIgMMqjvjs9HEqYkhAYq8aX3LrI0ks',
    appId: '1:306140297702:android:c20eeab3698ad2266c7e27',
    messagingSenderId: '306140297702',
    projectId: 'presensi-blockchain',
    storageBucket: 'presensi-blockchain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-NrjRHb80x4HsjgEqWHmRFhTa6cGMBSE',
    appId: '1:306140297702:ios:c1bd03b0ddcfc9b06c7e27',
    messagingSenderId: '306140297702',
    projectId: 'presensi-blockchain',
    storageBucket: 'presensi-blockchain.appspot.com',
    iosBundleId: 'com.example.presensiBlockchain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-NrjRHb80x4HsjgEqWHmRFhTa6cGMBSE',
    appId: '1:306140297702:ios:c1bd03b0ddcfc9b06c7e27',
    messagingSenderId: '306140297702',
    projectId: 'presensi-blockchain',
    storageBucket: 'presensi-blockchain.appspot.com',
    iosBundleId: 'com.example.presensiBlockchain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-w3fRjkMovOwgDDq2piNOh08dSRnPNmM',
    appId: '1:306140297702:web:814e0940182f47816c7e27',
    messagingSenderId: '306140297702',
    projectId: 'presensi-blockchain',
    authDomain: 'presensi-blockchain.firebaseapp.com',
    storageBucket: 'presensi-blockchain.appspot.com',
    measurementId: 'G-Z1N64HLT98',
  );

}